from snakemake.utils import min_version


# Configuration
configfile: "config/config.yaml"


# Settings
min_version("7.32.4")


# Define modules
module setup:
    snakefile:
        "rules/setup.smk"
    config:
        config


module genes:
    snakefile:
        "rules/genes.smk"
    config:
        config


# Import modules
use rule * from setup as setup_*


use rule * from genes as genes_*


###
# Rules
###


rule all:
    input:
        rules.genes_all.input,
    default_target: True
