from snakemake.utils import min_version


# Configuration
configfile: "config/config.yaml"


# Settings
min_version("7.32.4")


# Modules
module gencode:
    snakefile:
        "rules/gencode.smk"
    config:
        config["GENCODE"]


# Import modules
use rule * from gencode as gencode_*


###
# Rules
###


rule all:
    message:
        """
        DEPLOYING GENCODE...
        """
    input:
        rules.gencode_all.input,
